// Code generated by firmware embedder; DO NOT EDIT.

package cyw4343w

const Nvram = "manfid=0x2d0\x00prodid=0x0726\x00vendid=0x14e4\x00devid=0x43e2\x00boardtype=0x0726\x00boardrev=0x1202\x00boardnum=22\x00macaddr=00:90:4c:c5:12:38\x00sromrev=11\x00boardflags=0x00404201\x00boardflags3=0x08000000\x00xtalfreq=37400\x00nocrc=1\x00ag0=0\x00aa2g=1\x00ccode=ALL\x00extpagain2g=0\x00pa2ga0=-145,6667,-751\x00AvVmid_c0=0x0,0xc8\x00cckpwroffset0=2\x00maxp2ga0=74\x00cckbw202gpo=0\x00legofdmbw202gpo=0x88888888\x00mcsbw202gpo=0xaaaaaaaa\x00propbw202gpo=0xdd\x00ofdmdigfilttype=18\x00ofdmdigfilttypebe=18\x00papdmode=1\x00papdvalidtest=1\x00pacalidx2g=48\x00papdepsoffset=-22\x00papdendidx=58\x00il0macaddr=00:90:4c:c5:12:38\x00wl0id=0x431b\x00muxenab=0x10\x00swdiv_en=1\x00swdiv_gpio=1\x00\x00\x00"
